# Generated by Codex on 2026-03-12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_movie_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="original_language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original language code (e.g. en, hi)",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="search_history", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("view", "View"), ("rate", "Rate"), ("watchlist_add", "Watchlist Add"), ("watchlist_remove", "Watchlist Remove"), ("search", "Search"), ("chatbot_query", "Chatbot Query")], max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("movie", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="activities", to="api.movie")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="activities", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="WatchHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("movie", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="watch_history", to="api.movie")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="watch_history", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["user"], name="api_search_user_id_a48b97_idx"),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["created_at"], name="api_search_created_4045c9_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["user", "action"], name="api_userac_user_id_6fc4b4_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["created_at"], name="api_userac_created_1a2a49_idx"),
        ),
        migrations.AddIndex(
            model_name="watchhistory",
            index=models.Index(fields=["user"], name="api_watchh_user_id_19b3dd_idx"),
        ),
        migrations.AddIndex(
            model_name="watchhistory",
            index=models.Index(fields=["movie"], name="api_watchh_movie_i_2448e7_idx"),
        ),
        migrations.AddIndex(
            model_name="watchhistory",
            index=models.Index(fields=["viewed_at"], name="api_watchh_viewed_3ae2a5_idx"),
        ),
    ]
