# Generated by Codex on 2026-03-12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_activity_and_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="keywords",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated keywords for content-based similarity",
            ),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("watched", "Watched"),
                    ("rated", "Rated"),
                    ("searched", "Searched"),
                    ("added_watchlist", "Added Watchlist"),
                    ("removed_watchlist", "Removed Watchlist"),
                    ("chatbot_query", "Chatbot Query"),
                ],
                max_length=32,
                default="watched",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useractivity",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_genres", models.CharField(blank=True, default="", help_text="Comma-separated genres", max_length=255)),
                ("preferred_industry", models.CharField(blank=True, default="", help_text="e.g. bollywood, hollywood", max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="preference", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["user", "action_type"], name="api_userac_user_id_action_type_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(fields=["timestamp"], name="api_userac_timestamp_idx"),
        ),
    ]
