# Generated by Codex on 2026-03-14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_user_preferences_and_recommender_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMoviePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preference", models.CharField(choices=[("love", "Love"), ("like", "Like"), ("dislike", "Dislike")], max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("movie", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="movie_preferences", to="api.movie")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="movie_preferences", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "movie")},
            },
        ),
        migrations.AddIndex(
            model_name="usermoviepreference",
            index=models.Index(fields=["user"], name="api_usermoviepref_user_id_idx"),
        ),
        migrations.AddIndex(
            model_name="usermoviepreference",
            index=models.Index(fields=["movie"], name="api_usermoviepref_movie_id_idx"),
        ),
        migrations.AddIndex(
            model_name="usermoviepreference",
            index=models.Index(fields=["preference"], name="api_usermoviepref_preference_idx"),
        ),
    ]

