# Generated by Django 5.2.12 on 2026-03-14 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_movie_preference'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractivity',
            name='api_userac_user_id_6fc4b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='api_userac_created_1a2a49_idx',
        ),
        migrations.RenameIndex(
            model_name='searchhistory',
            new_name='api_searchh_user_id_34f1fd_idx',
            old_name='api_search_user_id_a48b97_idx',
        ),
        migrations.RenameIndex(
            model_name='searchhistory',
            new_name='api_searchh_created_bb923c_idx',
            old_name='api_search_created_4045c9_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='api_useract_user_id_838c61_idx',
            old_name='api_userac_user_id_action_type_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='api_useract_timesta_199b62_idx',
            old_name='api_userac_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoviepreference',
            new_name='api_usermov_user_id_82c976_idx',
            old_name='api_usermoviepref_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoviepreference',
            new_name='api_usermov_movie_i_77ea25_idx',
            old_name='api_usermoviepref_movie_id_idx',
        ),
        migrations.RenameIndex(
            model_name='usermoviepreference',
            new_name='api_usermov_prefere_f81ae5_idx',
            old_name='api_usermoviepref_preference_idx',
        ),
        migrations.RenameIndex(
            model_name='watchhistory',
            new_name='api_watchhi_user_id_f3b508_idx',
            old_name='api_watchh_user_id_19b3dd_idx',
        ),
        migrations.RenameIndex(
            model_name='watchhistory',
            new_name='api_watchhi_movie_i_89b020_idx',
            old_name='api_watchh_movie_i_2448e7_idx',
        ),
        migrations.RenameIndex(
            model_name='watchhistory',
            new_name='api_watchhi_viewed__461bd7_idx',
            old_name='api_watchh_viewed_3ae2a5_idx',
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(blank=True, choices=[('watched', 'Watched'), ('rated', 'Rated'), ('searched', 'Searched'), ('added_watchlist', 'Added Watchlist'), ('removed_watchlist', 'Removed Watchlist'), ('chatbot_query', 'Chatbot Query'), ('liked', 'Liked'), ('loved', 'Loved'), ('disliked', 'Disliked')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action_type',
            field=models.CharField(choices=[('watched', 'Watched'), ('rated', 'Rated'), ('searched', 'Searched'), ('added_watchlist', 'Added Watchlist'), ('removed_watchlist', 'Removed Watchlist'), ('chatbot_query', 'Chatbot Query'), ('liked', 'Liked'), ('loved', 'Loved'), ('disliked', 'Disliked')], max_length=32),
        ),
    ]
