# Generated by Django 6.0.2 on 2026-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_genres",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Onboarding preferred genres as names or ids",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_vibe",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Onboarding vibe preference",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="watch_frequency",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Onboarding watch frequency preference",
                max_length=32,
            ),
        ),
    ]
