# Generated by Django 6.0.2 on 2026-03-22 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_onboarding_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('content_based', 'Content-Based Filtering'), ('collaborative', 'Collaborative Filtering'), ('hybrid', 'Hybrid Scoring'), ('language', 'Language Preference'), ('cold_start', 'Cold Start / Onboarding')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('training', 'Training'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['model_type'], name='api_recomme_model_t_93d45c_idx'), models.Index(fields=['status'], name='api_recomme_status_0bf34f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_tmdb_ids', models.JSONField(default=list)),
                ('signal_used', models.CharField(blank=True, max_length=50)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_logs', to='api.recommendermodel')),
            ],
            options={
                'indexes': [models.Index(fields=['model', 'created_at'], name='api_modelpr_model_i_0eae63_idx'), models.Index(fields=['user', 'created_at'], name='api_modelpr_user_id_811ddf_idx'), models.Index(fields=['signal_used'], name='api_modelpr_signal__f02e75_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelAccuracySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('total_recommendations', models.IntegerField(default=0)),
                ('total_positives', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_snapshots', to='api.recommendermodel')),
            ],
            options={
                'indexes': [models.Index(fields=['model', 'computed_at'], name='api_modelac_model_i_e1f2d9_idx')],
            },
        ),
    ]
