# Generated by Django 6.0.2 on 2026-03-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_recommendermodel_modelpredictionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccuracysnapshot',
            name='metric_type',
            field=models.CharField(choices=[('prediction_accuracy', 'Prediction Accuracy'), ('catalog_quality', 'Catalog Quality')], default='prediction_accuracy', max_length=32),
        ),
        migrations.AddField(
            model_name='modelaccuracysnapshot',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
