# Generated by Django 6.0.2 on 2026-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_modelaccuracysnapshot_metric_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelpredictionlog",
            name="frontend_render_ms",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
